__version__ = '0.1.33'
__title__ = "turbosearch"
__description__ = "The most powerfull Automated url finder/crawler."
__url__ = "https://github.com/helviojunior/turbosearch"
__build__ = 0x63c789cc
__author__ = "Helvio Junior  (M4v3r1ck)"
__author_email__ = "helvio.junior@sec4us.com.br"
__license__ = "GPL-3.0"
__copyright__ = "Copyright Helvio Junior"
