site_name: TurboSearch
theme: 
  name: readthedocs
  locale: en
  language: en
nav:
- Home: index.md
- Português:
  - Overview: pt/index.md
  - Parâmetros: pt/parameters.md
- English:
  - Overview: en/index.md
  - Parameters: en/parameters.md
